__interface Mmcme2MMCME2_ADV {
    __parameter const char *     BANDWIDTH;
    __input  __int(1)         CLKFBIN;
    __output __int(1)         CLKFBOUT;
    __output __int(1)         CLKFBOUTB;
    __parameter float            CLKFBOUT_MULT_F;
    __parameter float            CLKFBOUT_PHASE;
    __parameter const char *     CLKFBOUT_USE_FINE_PS;
    __output __int(1)         CLKFBSTOPPED;
    __input  __int(1)         CLKIN1;
    __parameter float            CLKIN1_PERIOD;
    __input  __int(1)         CLKIN2;
    __parameter float            CLKIN2_PERIOD;
    __input  __int(1)         CLKINSEL;
    __output __int(1)         CLKINSTOPPED;
    __output __int(1)         CLKOUT0;
    __output __int(1)         CLKOUT0B;
    __parameter float            CLKOUT0_DIVIDE_F;
    __parameter float            CLKOUT0_DUTY_CYCLE;
    __parameter float            CLKOUT0_PHASE;
    __parameter const char *     CLKOUT0_USE_FINE_PS;
    __output __int(1)         CLKOUT1;
    __output __int(1)         CLKOUT1B;
    __parameter int              CLKOUT1_DIVIDE;
    __parameter float            CLKOUT1_DUTY_CYCLE;
    __parameter float            CLKOUT1_PHASE;
    __parameter const char *     CLKOUT1_USE_FINE_PS;
    __output __int(1)         CLKOUT2;
    __output __int(1)         CLKOUT2B;
    __parameter int              CLKOUT2_DIVIDE;
    __parameter float            CLKOUT2_DUTY_CYCLE;
    __parameter float            CLKOUT2_PHASE;
    __parameter const char *     CLKOUT2_USE_FINE_PS;
    __output __int(1)         CLKOUT3;
    __output __int(1)         CLKOUT3B;
    __parameter int              CLKOUT3_DIVIDE;
    __parameter float            CLKOUT3_DUTY_CYCLE;
    __parameter float            CLKOUT3_PHASE;
    __parameter const char *     CLKOUT3_USE_FINE_PS;
    __output __int(1)         CLKOUT4;
    __parameter const char *     CLKOUT4_CASCADE;
    __parameter int              CLKOUT4_DIVIDE;
    __parameter float            CLKOUT4_DUTY_CYCLE;
    __parameter float            CLKOUT4_PHASE;
    __parameter const char *     CLKOUT4_USE_FINE_PS;
    __output __int(1)         CLKOUT5;
    __parameter int              CLKOUT5_DIVIDE;
    __parameter float            CLKOUT5_DUTY_CYCLE;
    __parameter float            CLKOUT5_PHASE;
    __parameter const char *     CLKOUT5_USE_FINE_PS;
    __output __int(1)         CLKOUT6;
    __parameter int              CLKOUT6_DIVIDE;
    __parameter float            CLKOUT6_DUTY_CYCLE;
    __parameter float            CLKOUT6_PHASE;
    __parameter const char *     CLKOUT6_USE_FINE_PS;
    __parameter const char *     COMPENSATION;
    __input  __int(7)         DADDR;
    __input  __int(1)         DCLK;
    __input  __int(1)         DEN;
    __input  __int(16)        DI;
    __parameter int              DIVCLK_DIVIDE;
    __output __int(16)        DO;
    __output __int(1)         DRDY;
    __input  __int(1)         DWE;
    __parameter logic            IS_CLKINSEL_INVERTED;
    __parameter logic            IS_PSEN_INVERTED;
    __parameter logic            IS_PSINCDEC_INVERTED;
    __parameter logic            IS_PWRDWN_INVERTED;
    __parameter logic            IS_RST_INVERTED;
    __output __int(1)         LOCKED;
    __input  __int(1)         PSCLK;
    __output __int(1)         PSDONE;
    __input  __int(1)         PSEN;
    __input  __int(1)         PSINCDEC;
    __input  __int(1)         PWRDWN;
    __parameter float            REF_JITTER1;
    __parameter float            REF_JITTER2;
    __input  __int(1)         RST;
    __parameter const char *     SS_EN;
    __parameter const char *     SS_MODE;
    __parameter int              SS_MOD_PERIOD;
    __parameter const char *     STARTUP_WAIT;
};
__emodule MMCME2_ADV {
    Mmcme2MMCME2_ADV _;
};
